id: P009447
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG9029
  title: 'དུས་འཁོར་རྒྱུད་སྙིང་བསྡུས་པ། '
  author: ''
  volumes:
    6beaa6d69d1c471eb5e45638552c63c2:
      image_group_id: I1KG9050
      title: ''
      volume_number: 1
      total_pages: 510
